package solutions.s41to50;

/**
 * Problem 44:
 * <p>
 * Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
 * 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
 * It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
 * Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
 */

public class Problem44 {

    // we will generate 10000 pentagonal numbers assuming minmum difference lies within this range
    private static int LIMIT = 10000;

    public static void main(String args[]) throws Exception {
        System.out.println(minimumPentagonalDifference());
    }

    private static int minimumPentagonalDifference() {
        int min = Integer.MAX_VALUE;
        for (int i = 1; i < LIMIT; i++) {
            int firstNumber = (i * (3 * i - 1)) / 2;
            for (int j = 1; j < LIMIT; j++) {
                int secondNumber = (j * (3 * j - 1)) / 2;

                if (firstNumber != secondNumber
                        && isPentagonalNumber(firstNumber + secondNumber)
                        && isPentagonalNumber(firstNumber - secondNumber)) {
                    if (min > firstNumber - secondNumber)
                        min = firstNumber - secondNumber;
                }
            }
        }
        return min;
    }

    private static boolean isPentagonalNumber(int x) {
        double n = (Math.sqrt(24.0 * (double) x + 1.0) + 1.0) / 6.0;
        return (int) n == n;
    }
}
